# Generated by Django 4.2.2 on 2023-06-30 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='apps/', verbose_name='Logo')),
                ('notify_by_email', models.BooleanField(default=False, verbose_name='Notify by email')),
                ('admins', models.ManyToManyField(related_name='apps', to=settings.AUTH_USER_MODEL, verbose_name='Administrators')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['name'],
            },
        ),
    ]
