# Generated by Django 4.2.2 on 2023-06-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='use_health_check',
            field=models.BooleanField(default=False, verbose_name='Use Django health check'),
        ),
        migrations.AddField(
            model_name='application',
            name='use_metrics',
            field=models.BooleanField(default=False, verbose_name='Use Django Prometheus metrics'),
        ),
    ]
