# Generated by Django 4.2.2 on 2023-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_application_use_health_check_application_use_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bg_update',
            field=models.BooleanField(default=False, verbose_name='Update in background'),
        ),
        migrations.AddField(
            model_name='application',
            name='db_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Database Backend'),
        ),
        migrations.AddField(
            model_name='application',
            name='disk_usage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Disk Usage'),
        ),
        migrations.AddField(
            model_name='application',
            name='http_status',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP Status'),
        ),
        migrations.AddField(
            model_name='application',
            name='mem_usage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Memory Usage'),
        ),
        migrations.AddField(
            model_name='application',
            name='migration_health',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Migration Health Check'),
        ),
    ]
