# Generated by Django 4.2.2 on 2023-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_application_bg_update_application_db_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='db_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mem_usage',
        ),
        migrations.RemoveField(
            model_name='application',
            name='migration_health',
        ),
        migrations.AddField(
            model_name='application',
            name='health_check',
            field=models.JSONField(blank=True, null=True, verbose_name='Health Check Status'),
        ),
    ]
