# Generated by Django 4.2.2 on 2023-07-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_application_db_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
