# Generated by Django 4.2.2 on 2023-07-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_application_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('cpu_time', models.FloatField(default=0.0, verbose_name='CPU time')),
                ('cpu_percent', models.FloatField(default=0.0, verbose_name='CPU percent')),
                ('mem_rss', models.FloatField(default=0.0, verbose_name='Memory (resident)')),
                ('mem_vrt', models.FloatField(default=0.0, verbose_name='Memory (virtual)')),
                ('mem_percent', models.FloatField(default=0.0, verbose_name='Memnory percent')),
            ],
            options={
                'verbose_name': 'Process metric',
                'verbose_name_plural': 'Process metrics',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='use_metrics',
            field=models.BooleanField(default=False, verbose_name='Use psutil metrics'),
        ),
    ]
