# Generated by Django 4.2.2 on 2023-07-02 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_processmetric_alter_application_use_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmetric',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.application', verbose_name='Application'),
            preserve_default=False,
        ),
    ]
