# Generated by Django 4.2.2 on 2023-07-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_processmetric_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last update'),
        ),
    ]
