# Generated by Django 4.2.3 on 2023-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_application_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_cpu_percent',
            field=models.FloatField(default=80.0, verbose_name='Max. CPU Percentage'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_mem_percent',
            field=models.FloatField(default=80.0, verbose_name='Max. Memory Percentage'),
        ),
    ]
