# Generated by Django 4.2.3 on 2023-07-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_application_max_cpu_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='alert_sent',
            field=models.BooleanField(default=False, verbose_name='Alert sent'),
        ),
    ]
