# Generated by Django 4.2.3 on 2023-07-05 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_application_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmetric',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='app.application', verbose_name='Application'),
        ),
    ]
