# Generated by Django 4.2.3 on 2023-07-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_processmetric_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_cpu_time',
            field=models.FloatField(default=80.0, verbose_name='Max. CPU Time'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_mem_rss',
            field=models.FloatField(default=80.0, verbose_name='Max. Memory (resident)'),
        ),
        migrations.AddField(
            model_name='application',
            name='max_mem_vrt',
            field=models.FloatField(default=80.0, verbose_name='Max. Memory (virtual)'),
        ),
    ]
