# Generated by Django 4.2.3 on 2023-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_application_max_cpu_time_application_max_mem_rss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='max_cpu_percent',
            field=models.FloatField(default=0.8, verbose_name='Max. CPU Percentage'),
        ),
        migrations.AlterField(
            model_name='application',
            name='max_mem_percent',
            field=models.FloatField(default=0.8, verbose_name='Max. Memory Percentage'),
        ),
        migrations.AlterField(
            model_name='application',
            name='max_mem_rss',
            field=models.FloatField(default=5000000000.0, verbose_name='Max. Memory (resident)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='max_mem_vrt',
            field=models.FloatField(default=5000000000.0, verbose_name='Max. Memory (virtual)'),
        ),
    ]
