# Generated by Django 4.2.3 on 2023-07-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_application_max_cpu_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='max_cpu_time',
        ),
        migrations.RemoveField(
            model_name='application',
            name='max_mem_rss',
        ),
        migrations.RemoveField(
            model_name='application',
            name='max_mem_vrt',
        ),
        migrations.RemoveField(
            model_name='processmetric',
            name='cpu_time',
        ),
        migrations.RemoveField(
            model_name='processmetric',
            name='mem_rss',
        ),
        migrations.RemoveField(
            model_name='processmetric',
            name='mem_vrt',
        ),
    ]
