# Generated by Django 4.2.3 on 2023-07-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_application_max_cpu_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessMetric',
            new_name='SystemMetric',
        ),
    ]
