# Generated by Django 4.2.3 on 2023-07-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_systemmetric_options_application_metric_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('typus', models.CharField(max_length=20, verbose_name='Type')),
                ('value', models.CharField(max_length=20, verbose_name='Value')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to='app.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Status record',
                'verbose_name_plural': 'Status records',
                'ordering': ['timestamp'],
            },
        ),
    ]
