# Generated by Django 4.2.3 on 2023-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_statusrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusrecord',
            name='typus',
            field=models.CharField(max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='statusrecord',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Value'),
        ),
    ]
