# Generated by Django 4.2.3 on 2023-07-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_statusrecord_typus_alter_statusrecord_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('typus', models.CharField(max_length=50, verbose_name='Type')),
                ('value', models.CharField(max_length=50, verbose_name='Value')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='app.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='StatusRecord',
        ),
    ]
