# Generated by Django 4.2.3 on 2023-08-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alert_delete_statusrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='frequency',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (30, '30')], default=15, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='State'),
        ),
    ]
