# Generated by Django 4.2.3 on 2023-08-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_application_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='frequency',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (30, '30')], default=15, verbose_name='State'),
        ),
    ]
