# Generated by Django 4.2.3 on 2023-08-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_application_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Alert', 'verbose_name_plural': 'Alerts'},
        ),
    ]
