# Generated by Django 4.2.4 on 2023-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_alert_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Timeout'),
        ),
        migrations.AlterField(
            model_name='application',
            name='frequency',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (30, '30')], default=15, verbose_name='Test frequency'),
        ),
    ]
