# Generated by Django 6.0.6 on 2026-07-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_application_timeout_alter_application_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cert_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificate expiration'),
        ),
        migrations.AddField(
            model_name='application',
            name='cert_issue',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certificate issue'),
        ),
        migrations.AddField(
            model_name='application',
            name='check_cert',
            field=models.BooleanField(default=False, verbose_name='Check certificate'),
        ),
    ]
