# Generated by Django 6.0.6 on 2026-07-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_application_cert_expiration_application_cert_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='typus',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
    ]
