# Generated by Django 6.0.6 on 2026-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_alert_typus_alter_alert_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cert_status',
            field=models.BooleanField(default=False, verbose_name='Certificate status'),
        ),
    ]
