# Generated by Django 6.0.6 on 2026-07-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_application_cert_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='cert_status',
            new_name='cert_expire_status',
        ),
    ]
