# Generated by Django 6.0.6 on 2026-07-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_cert_status_application_cert_expire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cert_expire_status',
            field=models.BooleanField(default=False, verbose_name='Certificate will expire'),
        ),
    ]
